sudo: required

services: docker

before_install:
  - docker login -u sugar777 -p 7a6aec11-f634-4460-a436-2b399f4e3094
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test
